query fetchAdminData($tokenId: String) {
  getPages {
    name
    slug
    isInMenu
    pageComponents
    pageMenuParent
    pageMenuOrder
    title
    description
    keywords
    id
    author
  }
  getSingleUser(tokenId: $tokenId) {
    firstName
    lastName
    email
    id
  }
  getComponentContent {
    pageInfo {
      id
      name
      slug
    }
    fields {
      autocomplete
      component
      disabled
      elementName
      formPart
      id
      key
      label
      options
      type
      required
      validation {
        validator
        validated
        validationMessage
      }
      value
      visible
    }
  }
}

mutation createComponentContent($input: ComponentContentInput) {
  createComponentContent(input: $input) {
    pageInfo {
      id
      name
      slug
    }
  }
}

mutation deletePage($id : String) {
  deletePage(id: $id) {
    name
  }
}

mutation createPage($input: PageInput) {
  createPage(input: $input) {
    name
    slug
    isInMenu
    pageComponents
    pageMenuParent
    pageMenuOrder
    title
    description
    keywords
    id
    author
  }
}

mutation deleteUser($id: String) {
  deleteUser(id: $id) {
    id
  }
}

mutation editUser($input: UserInput) {
  editUser(input: $input) {
    firstName
    lastName
    email
    id
  }
}

mutation createUser($input: UserInput) {
  createUser(input: $input) {
    email
  }
}