query fetchSinglePage($slug: String) {
  getSinglePage(slug: $slug) {
    name
    pageComponents
    pageMenuParent
    id
  }
  getComponentContentBySlug(slug: $slug) {
    pageInfo {
      id
      name
      slug
    }
    fields {
      component
      disabled
      elementName
      formPart
      id
      key
      label
      options
      type
      required
      validation {
        validator
        validated
        validationMessage
      }
      value
      visible
    }
  }
}