mutation deleteUser($id: String) {
  deleteUser(id: $id) {
    id
  }
}

mutation editUser($input: UserInput) {
  editUser(input: $input) {
    firstName
    lastName
    email
    id
  }
}

mutation createUser($input: UserInput) {
  createUser(input: $input) {
    email
  }
}